# Reads bootstrap.ann and generates bootstrap_code.generated.hpp
# Usage: pwsh -File generate_bootstrap.ps1
# Run from any directory; paths are relative to this script's location.

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
$inputFile  = Join-Path $scriptDir "bootstrap.ann"
$outputFile = Join-Path $scriptDir "bootstrap_code.generated.hpp"

$content = Get-Content -Raw -Path $inputFile

$hpp = @"
// AUTO-GENERATED - do not edit manually.
// Source: bootstrap.ann
// Regenerated by generate_bootstrap.ps1 on every Pre-Build.

const char annium_bootstrap_code[] = R"#($content)#";
"@

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($outputFile, $hpp, $utf8NoBom)
Write-Host "Generated: $outputFile"
