name: Windows MSVC Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            submodules: recursive
      
      - name: Clone vcpkg
        run: git clone https://github.com/microsoft/vcpkg.git vcpkg

      - name: Bootstrap vcpkg
        run: .\vcpkg\bootstrap-vcpkg.bat

      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
            path: |
              ${{ github.workspace }}/vcpkg_installed
            key: vcpkg-${{ runner.os }}-${{ steps.vcpkg_ref.outputs.ref }}-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json', 'triplets/**') }}
            restore-keys: |
              vcpkg-${{ runner.os }}-
      
      - name: Install Dependencies
        run: .\vcpkg\vcpkg.exe install --triplet x64-windows-cpp23 --overlay-triplets="triplets"
                  
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build solution
        run: msbuild annium.sln /p:Configuration=Release

      - name: Run tests
        run: |
          cd x64/Release
          $env:PATH += ";${{ github.workspace }}\vcpkg_installed\x64-windows-cpp23\bin"
          $env:TESTS_HOME = "${{ github.workspace }}\tests"
          .\annium_tests.exe
